//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploiye
    {
        public int NumEmp { get; set; }
        public string NomEmp { get; set; }
        public Nullable<System.DateTime> DateEmp { get; set; }
        public Nullable<decimal> Salaire { get; set; }
        public string Fonction { get; set; }
    }
}
