//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PhotelEntities : DbContext
    {
        public PhotelEntities()
            : base("name=PhotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Emploiye> Emploiye { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Chambre> Chambre { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<mailing> mailing { get; set; }
    
        public virtual ObjectResult<ClientNonPayee_Result> ClientNonPayee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientNonPayee_Result>("ClientNonPayee");
        }
    }
}
