//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int NumR { get; set; }
        public Nullable<int> CodeClient { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<System.DateTime> Datef { get; set; }
        public Nullable<int> NumChambre { get; set; }
        public Nullable<int> NombrePlace { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Chambre Chambre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
